use anchor_lang::prelude::*;
use anchor_lang::system_program;

// V-19 FIX: Replace this placeholder with the real program ID generated by `anchor build`.
// NEVER deploy with the system program address (all 1s) as the program ID.
// Steps: 1) run `anchor build`, 2) copy the output program ID, 3) paste it here.
declare_id!("11111111111111111111111111111111"); // ← MUST be replaced before any deployment

/// TORA Exchange — Tokenized Operational Record Asset Marketplace
/// Smart contract handling:
///   1. Asset listing (suppliers register their tokenized data)
///   2. License purchase (buyers pay for access, held in escrow — V-12 fix)
///   3. Revenue split (automatic distribution to supplier, platform, partner)
///   4. License tracking (on-chain record of all active licenses)
///   5. License verification with expiry enforcement (V-10 fix)
///   6. Dispute resolution via admin arbitration (V-12 fix)

#[program]
pub mod tora_contracts {
    use super::*;

    /// Initialize the TORA Exchange configuration.
    /// Called once by the platform admin (BITS).
    /// V-11 FIX: partner_treasury is now stored in Exchange state and constrained on every call.
    pub fn initialize(
        ctx: Context<Initialize>,
        platform_fee_bps: u16,     // Platform fee in basis points (e.g., 1500 = 15%)
        partner_fee_bps: u16,      // Partner fee in basis points (e.g., 500 = 5%)
        partner_treasury: Pubkey,  // V-11 FIX: authorized partner treasury address
    ) -> Result<()> {
        require!(platform_fee_bps + partner_fee_bps <= 5000, ToraError::FeeTooHigh); // Max 50% total fees

        let exchange = &mut ctx.accounts.exchange;
        exchange.authority = ctx.accounts.authority.key();
        exchange.platform_fee_bps = platform_fee_bps;
        exchange.partner_fee_bps = partner_fee_bps;
        exchange.partner_treasury = partner_treasury; // V-11 FIX: stored on-chain
        exchange.total_listings = 0;
        exchange.total_licenses_sold = 0;
        exchange.total_volume_lamports = 0;
        exchange.bump = ctx.bumps.exchange;

        msg!("TORA Exchange initialized. Platform fee: {}bps, Partner fee: {}bps, Partner treasury: {}",
             platform_fee_bps, partner_fee_bps, partner_treasury);
        Ok(())
    }

    /// Register a new data asset on the exchange.
    /// Called by data suppliers who want to list their tokenized operational records.
    pub fn list_asset(
        ctx: Context<ListAsset>,
        asset_id: String,
        name: String,
        industry: String,
        price_lamports: u64,       // Monthly license price in lamports
        record_count: u64,         // Number of records in the corpus
        data_hash: [u8; 32],       // SHA-256 hash of the data corpus for verification
    ) -> Result<()> {
        require!(asset_id.len() <= 32, ToraError::StringTooLong);
        require!(name.len() <= 64, ToraError::StringTooLong);
        require!(industry.len() <= 32, ToraError::StringTooLong);
        require!(price_lamports > 0, ToraError::InvalidPrice);

        let listing = &mut ctx.accounts.listing;
        listing.supplier = ctx.accounts.supplier.key();
        listing.asset_id = asset_id.clone();
        listing.name = name;
        listing.industry = industry;
        listing.price_lamports = price_lamports;
        listing.record_count = record_count;
        listing.data_hash = data_hash;
        listing.is_active = true;
        listing.licenses_sold = 0;
        listing.total_revenue = 0;
        listing.created_at = Clock::get()?.unix_timestamp;
        listing.bump = ctx.bumps.listing;

        let exchange = &mut ctx.accounts.exchange;
        exchange.total_listings += 1;

        msg!("Asset listed: {} | Price: {} lamports/mo | Records: {}",
             asset_id, price_lamports, record_count);
        Ok(())
    }

    /// Purchase a license to access a listed data asset.
    /// V-12 FIX: Funds are held in a PDA escrow and NOT immediately disbursed to the supplier.
    ///           The buyer must call release_payment after verifying the data, or may cancel
    ///           within the dispute window. Admin can arbitrate disputes.
    pub fn purchase_license(
        ctx: Context<PurchaseLicense>,
        license_months: u8,        // Duration of license in months (1-12)
    ) -> Result<()> {
        require!(license_months >= 1 && license_months <= 12, ToraError::InvalidDuration);
        require!(ctx.accounts.listing.is_active, ToraError::ListingInactive);

        let listing = &ctx.accounts.listing;
        let exchange = &ctx.accounts.exchange;

        // Calculate total payment
        let total_payment = listing.price_lamports
            .checked_mul(license_months as u64)
            .ok_or(ToraError::Overflow)?;

        // Calculate fee splits (basis points: 10000 = 100%)
        let platform_fee = total_payment
            .checked_mul(exchange.platform_fee_bps as u64)
            .ok_or(ToraError::Overflow)?
            .checked_div(10000)
            .ok_or(ToraError::Overflow)?;

        let partner_fee = total_payment
            .checked_mul(exchange.partner_fee_bps as u64)
            .ok_or(ToraError::Overflow)?
            .checked_div(10000)
            .ok_or(ToraError::Overflow)?;

        let supplier_payment = total_payment
            .checked_sub(platform_fee)
            .ok_or(ToraError::Overflow)?
            .checked_sub(partner_fee)
            .ok_or(ToraError::Overflow)?;

        // V-12 FIX: Transfer supplier's portion to the escrow PDA (held until release or cancel)
        system_program::transfer(
            CpiContext::new(
                ctx.accounts.system_program.to_account_info(),
                system_program::Transfer {
                    from: ctx.accounts.buyer.to_account_info(),
                    to: ctx.accounts.escrow.to_account_info(),
                },
            ),
            supplier_payment,
        )?;

        // Platform fee goes directly to BITS treasury (non-refundable service fee)
        system_program::transfer(
            CpiContext::new(
                ctx.accounts.system_program.to_account_info(),
                system_program::Transfer {
                    from: ctx.accounts.buyer.to_account_info(),
                    to: ctx.accounts.platform_treasury.to_account_info(),
                },
            ),
            platform_fee,
        )?;

        // V-11 FIX: Partner fee goes to constrained partner_treasury (verified against exchange state)
        if partner_fee > 0 {
            system_program::transfer(
                CpiContext::new(
                    ctx.accounts.system_program.to_account_info(),
                    system_program::Transfer {
                        from: ctx.accounts.buyer.to_account_info(),
                        to: ctx.accounts.partner_treasury.to_account_info(),
                    },
                ),
                partner_fee,
            )?;
        }

        // V-18 NOTE: license_months * 30 days is an approximation.
        // Months range from 28-31 days. This is a known billing simplification.
        // Document this in license terms: "30-day billing periods".
        let now = Clock::get()?.unix_timestamp;
        let expires_at = now + (license_months as i64 * 30 * 24 * 60 * 60);

        // Create license record
        let license = &mut ctx.accounts.license;
        license.buyer = ctx.accounts.buyer.key();
        license.listing = ctx.accounts.listing.key();
        license.supplier = listing.supplier;
        license.amount_paid = total_payment;
        license.supplier_escrowed = supplier_payment;  // tracks what's in escrow
        license.supplier_received = 0;                 // updated when released
        license.platform_received = platform_fee;
        license.partner_received = partner_fee;
        license.months = license_months;
        license.purchased_at = now;
        license.expires_at = expires_at;
        license.is_active = true;
        license.is_released = false;
        license.is_disputed = false;
        license.bump = ctx.bumps.license;

        // Update listing stats
        let listing = &mut ctx.accounts.listing;
        listing.licenses_sold += 1;
        listing.total_revenue += total_payment;

        // Update exchange stats
        let exchange = &mut ctx.accounts.exchange;
        exchange.total_licenses_sold += 1;
        exchange.total_volume_lamports += total_payment;

        msg!("License purchased! Total: {} | Escrowed for supplier: {} | Platform: {} | Partner: {}",
             total_payment, supplier_payment, platform_fee, partner_fee);
        Ok(())
    }

    /// V-12 FIX: Release escrowed payment to supplier after buyer verifies data delivery.
    /// Called by the buyer after confirming they have access to the licensed data.
    pub fn release_payment(ctx: Context<ReleasePayment>) -> Result<()> {
        let license = &mut ctx.accounts.license;
        require!(license.is_active, ToraError::LicenseInactive);
        require!(!license.is_released, ToraError::AlreadyReleased);
        require!(!license.is_disputed, ToraError::DisputeInProgress);

        let amount = license.supplier_escrowed;
        require!(amount > 0, ToraError::NothingToRelease);

        // Release escrow funds to supplier via PDA signer
        let escrow_seeds: &[&[u8]] = &[
            b"escrow",
            ctx.accounts.license.to_account_info().key.as_ref(),
            &[ctx.bumps.escrow],
        ];
        system_program::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.system_program.to_account_info(),
                system_program::Transfer {
                    from: ctx.accounts.escrow.to_account_info(),
                    to: ctx.accounts.supplier.to_account_info(),
                },
                &[escrow_seeds],
            ),
            amount,
        )?;

        license.is_released = true;
        license.supplier_received = amount;
        license.supplier_escrowed = 0;

        msg!("Payment released: {} lamports to supplier {}", amount, ctx.accounts.supplier.key());
        Ok(())
    }

    /// V-12 FIX: Cancel a license and refund the escrowed amount to the buyer.
    /// Only allowed within the dispute window (48 hours of purchase) and before data is released.
    pub fn cancel_and_refund(ctx: Context<CancelAndRefund>) -> Result<()> {
        let license = &mut ctx.accounts.license;
        require!(license.is_active, ToraError::LicenseInactive);
        require!(!license.is_released, ToraError::AlreadyReleased);
        require!(!license.is_disputed, ToraError::DisputeInProgress);

        // Enforce 48-hour refund window
        let now = Clock::get()?.unix_timestamp;
        let dispute_window_seconds: i64 = 48 * 60 * 60;
        require!(
            now <= license.purchased_at + dispute_window_seconds,
            ToraError::RefundWindowExpired
        );

        let amount = license.supplier_escrowed;
        require!(amount > 0, ToraError::NothingToRelease);

        // Refund from escrow to buyer
        let escrow_seeds: &[&[u8]] = &[
            b"escrow",
            ctx.accounts.license.to_account_info().key.as_ref(),
            &[ctx.bumps.escrow],
        ];
        system_program::transfer(
            CpiContext::new_with_signer(
                ctx.accounts.system_program.to_account_info(),
                system_program::Transfer {
                    from: ctx.accounts.escrow.to_account_info(),
                    to: ctx.accounts.buyer.to_account_info(),
                },
                &[escrow_seeds],
            ),
            amount,
        )?;

        license.is_active = false;
        license.supplier_escrowed = 0;

        msg!("License cancelled and {} lamports refunded to buyer {}", amount, ctx.accounts.buyer.key());
        Ok(())
    }

    /// V-12 FIX: Admin arbitration for disputed licenses.
    /// Called only by exchange.authority (BITS). Can direct escrowed funds to either party.
    pub fn admin_resolve(
        ctx: Context<AdminResolve>,
        release_to_supplier: bool,
    ) -> Result<()> {
        let license = &mut ctx.accounts.license;
        require!(license.is_active, ToraError::LicenseInactive);
        require!(!license.is_released, ToraError::AlreadyReleased);

        let amount = license.supplier_escrowed;
        require!(amount > 0, ToraError::NothingToRelease);

        let escrow_seeds: &[&[u8]] = &[
            b"escrow",
            ctx.accounts.license.to_account_info().key.as_ref(),
            &[ctx.bumps.escrow],
        ];

        if release_to_supplier {
            // Arbitrate in supplier's favor
            system_program::transfer(
                CpiContext::new_with_signer(
                    ctx.accounts.system_program.to_account_info(),
                    system_program::Transfer {
                        from: ctx.accounts.escrow.to_account_info(),
                        to: ctx.accounts.supplier.to_account_info(),
                    },
                    &[escrow_seeds],
                ),
                amount,
            )?;
            license.supplier_received = amount;
            license.is_released = true;
            msg!("Admin resolved: {} lamports released to supplier", amount);
        } else {
            // Arbitrate in buyer's favor (refund)
            system_program::transfer(
                CpiContext::new_with_signer(
                    ctx.accounts.system_program.to_account_info(),
                    system_program::Transfer {
                        from: ctx.accounts.escrow.to_account_info(),
                        to: ctx.accounts.buyer.to_account_info(),
                    },
                    &[escrow_seeds],
                ),
                amount,
            )?;
            license.is_released = true;
            msg!("Admin resolved: {} lamports refunded to buyer", amount);
        }

        license.is_disputed = false;
        license.is_active = false;
        license.supplier_escrowed = 0;

        Ok(())
    }

    /// SC-03 FIX: Raise a dispute on an active license.
    /// Only the buyer can initiate a dispute. Blocks release/cancel until admin resolves.
    pub fn raise_dispute(ctx: Context<RaiseDispute>) -> Result<()> {
        let license = &mut ctx.accounts.license;
        require!(license.is_active, ToraError::LicenseInactive);
        require!(!license.is_released, ToraError::PaymentAlreadyReleased);
        require!(!license.is_disputed, ToraError::AlreadyDisputed);

        license.is_disputed = true;

        msg!("Dispute raised by buyer {} on license {}", ctx.accounts.buyer.key(), ctx.accounts.license.key());
        Ok(())
    }

    /// V-10 FIX: Verify an active license and enforce expiry on-chain.
    /// This instruction MUST be called before granting data access.
    /// Returns error if license is expired or inactive — callers use this as an access gate.
    pub fn verify_license(ctx: Context<VerifyLicense>) -> Result<()> {
        let license = &mut ctx.accounts.license;

        require!(license.is_active, ToraError::LicenseInactive);
        require!(!license.is_disputed, ToraError::DisputeInProgress);

        let now = Clock::get()?.unix_timestamp;
        if now > license.expires_at {
            // Automatically deactivate expired licenses
            license.is_active = false;
            return err!(ToraError::LicenseExpired);
        }

        let days_remaining = (license.expires_at - now) / 86400;
        msg!("License {} is ACTIVE. Expires in {} days.", license.buyer, days_remaining);
        Ok(())
    }

    /// V-10 FIX: Explicitly expire a license after its term ends.
    /// Can be called by anyone — serves as a housekeeping instruction.
    pub fn expire_license(ctx: Context<ExpireLicense>) -> Result<()> {
        let license = &mut ctx.accounts.license;
        let now = Clock::get()?.unix_timestamp;

        require!(now > license.expires_at, ToraError::LicenseNotYetExpired);
        license.is_active = false;

        msg!("License expired and deactivated for buyer: {}", license.buyer);
        Ok(())
    }

    /// Deactivate a listing (supplier only).
    pub fn deactivate_listing(ctx: Context<DeactivateListing>) -> Result<()> {
        let listing = &mut ctx.accounts.listing;
        listing.is_active = false;
        msg!("Listing deactivated: {}", listing.asset_id);
        Ok(())
    }

    /// V-24 FIX: Close an expired/deactivated listing to reclaim rent.
    /// Can only be called by the original supplier.
    pub fn close_listing(_ctx: Context<CloseListing>) -> Result<()> {
        // The `close = supplier` constraint in CloseListing handles the SOL transfer automatically.
        msg!("Listing closed and rent reclaimed");
        Ok(())
    }

    /// V-24 FIX: Close an expired/released license to reclaim rent.
    /// Can only be called by the buyer.
    pub fn close_license(_ctx: Context<CloseLicense>) -> Result<()> {
        // The `close = buyer` constraint in CloseLicense handles the SOL transfer automatically.
        msg!("License closed and rent reclaimed");
        Ok(())
    }

    /// Update platform fees and partner treasury (admin only).
    /// V-11 FIX: Also allows updating the authorized partner_treasury address.
    pub fn update_fees(
        ctx: Context<UpdateFees>,
        platform_fee_bps: u16,
        partner_fee_bps: u16,
        partner_treasury: Option<Pubkey>,  // V-11: allows rotating partner treasury
    ) -> Result<()> {
        require!(platform_fee_bps + partner_fee_bps <= 5000, ToraError::FeeTooHigh);
        let exchange = &mut ctx.accounts.exchange;
        exchange.platform_fee_bps = platform_fee_bps;
        exchange.partner_fee_bps = partner_fee_bps;
        if let Some(pt) = partner_treasury {
            exchange.partner_treasury = pt;
        }
        msg!("Fees updated. Platform: {}bps, Partner: {}bps", platform_fee_bps, partner_fee_bps);
        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════
// ACCOUNT STRUCTURES
// ═══════════════════════════════════════════════════════════════

#[account]
pub struct Exchange {
    pub authority: Pubkey,              // Platform admin (BITS wallet)
    pub platform_fee_bps: u16,         // Platform fee basis points
    pub partner_fee_bps: u16,          // Partner fee basis points
    pub partner_treasury: Pubkey,      // V-11 FIX: Authorized partner treasury address
    pub total_listings: u64,           // Total assets listed
    pub total_licenses_sold: u64,      // Total licenses purchased
    pub total_volume_lamports: u64,    // Total transaction volume
    pub bump: u8,
}

#[account]
pub struct Listing {
    pub supplier: Pubkey,              // Data supplier wallet
    pub asset_id: String,              // Unique asset identifier (max 32 chars)
    pub name: String,                  // Asset name (max 64 chars)
    pub industry: String,              // Industry category (max 32 chars)
    pub price_lamports: u64,           // Monthly license price
    pub record_count: u64,             // Number of records in corpus
    pub data_hash: [u8; 32],           // SHA-256 hash for verification
    pub is_active: bool,               // Whether listing is active
    pub licenses_sold: u64,            // Number of licenses sold
    pub total_revenue: u64,            // Total revenue generated
    pub created_at: i64,               // Unix timestamp
    pub bump: u8,
}

#[account]
pub struct License {
    pub buyer: Pubkey,                 // Buyer wallet
    pub listing: Pubkey,               // Reference to listing
    pub supplier: Pubkey,              // Supplier wallet (for easy lookup)
    pub amount_paid: u64,              // Total amount paid
    pub supplier_escrowed: u64,        // V-12 FIX: Amount currently in escrow
    pub supplier_received: u64,        // Amount released to supplier
    pub platform_received: u64,        // Amount platform received
    pub partner_received: u64,         // Amount partner received
    pub months: u8,                    // License duration
    pub purchased_at: i64,             // Purchase timestamp
    pub expires_at: i64,               // Expiration timestamp (V-10 FIX: now enforced)
    pub is_active: bool,               // Whether license is active
    pub is_released: bool,             // V-12 FIX: Whether escrow has been released
    pub is_disputed: bool,             // V-12 FIX: Whether in dispute
    pub bump: u8,
}

// ═══════════════════════════════════════════════════════════════
// INSTRUCTION CONTEXTS
// ═══════════════════════════════════════════════════════════════

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = authority,
        // V-11 FIX: Added 32 bytes for partner_treasury Pubkey field
        space = 8 + 32 + 2 + 2 + 32 + 8 + 8 + 8 + 1,
        seeds = [b"exchange"],
        bump,
    )]
    pub exchange: Account<'info, Exchange>,
    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(asset_id: String)]
pub struct ListAsset<'info> {
    #[account(
        mut,
        seeds = [b"exchange"],
        bump = exchange.bump,
    )]
    pub exchange: Account<'info, Exchange>,
    #[account(
        init,
        payer = supplier,
        space = 8 + 32 + (4 + 32) + (4 + 64) + (4 + 32) + 8 + 8 + 32 + 1 + 8 + 8 + 8 + 1,
        seeds = [b"listing", asset_id.as_bytes()],
        bump,
    )]
    pub listing: Account<'info, Listing>,
    #[account(mut)]
    pub supplier: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct PurchaseLicense<'info> {
    #[account(
        mut,
        seeds = [b"exchange"],
        bump = exchange.bump,
    )]
    pub exchange: Account<'info, Exchange>,
    #[account(
        mut,
        constraint = listing.is_active @ ToraError::ListingInactive,
    )]
    pub listing: Account<'info, Listing>,
    #[account(
        init,
        payer = buyer,
        // V-12 FIX: Added is_released, is_disputed booleans + supplier_escrowed field
        space = 8 + 32 + 32 + 32 + 8 + 8 + 8 + 8 + 8 + 1 + 8 + 8 + 1 + 1 + 1 + 1,
        seeds = [b"license", buyer.key().as_ref(), listing.key().as_ref()],
        bump,
    )]
    pub license: Account<'info, License>,
    /// V-12 FIX: Escrow PDA holds supplier payment until release/refund
    #[account(
        init,
        payer = buyer,
        space = 0,
        seeds = [b"escrow", license.key().as_ref()],
        bump,
    )]
    pub escrow: SystemAccount<'info>,
    #[account(mut)]
    pub buyer: Signer<'info>,
    /// CHECK: Supplier wallet — constrained to listing.supplier
    #[account(mut, constraint = supplier.key() == listing.supplier @ ToraError::WrongSupplier)]
    pub supplier: AccountInfo<'info>,
    /// CHECK: Platform treasury — constrained to exchange.authority
    #[account(mut, constraint = platform_treasury.key() == exchange.authority @ ToraError::WrongTreasury)]
    pub platform_treasury: AccountInfo<'info>,
    /// V-11 FIX: Partner treasury — constrained to exchange.partner_treasury (no longer arbitrary)
    #[account(mut, constraint = partner_treasury.key() == exchange.partner_treasury @ ToraError::WrongPartnerTreasury)]
    pub partner_treasury: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct ReleasePayment<'info> {
    #[account(
        mut,
        constraint = license.buyer == buyer.key() @ ToraError::Unauthorized,
    )]
    pub license: Account<'info, License>,
    /// CHECK: Escrow PDA — verified by seeds
    #[account(
        mut,
        seeds = [b"escrow", license.key().as_ref()],
        bump,
    )]
    pub escrow: SystemAccount<'info>,
    #[account(mut)]
    pub buyer: Signer<'info>,
    /// CHECK: Supplier wallet — constrained to license.supplier
    #[account(mut, constraint = supplier.key() == license.supplier @ ToraError::WrongSupplier)]
    pub supplier: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct CancelAndRefund<'info> {
    #[account(
        mut,
        constraint = license.buyer == buyer.key() @ ToraError::Unauthorized,
    )]
    pub license: Account<'info, License>,
    /// CHECK: Escrow PDA — verified by seeds
    #[account(
        mut,
        seeds = [b"escrow", license.key().as_ref()],
        bump,
    )]
    pub escrow: SystemAccount<'info>,
    #[account(mut)]
    pub buyer: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct AdminResolve<'info> {
    #[account(
        mut,
        seeds = [b"exchange"],
        bump = exchange.bump,
        constraint = exchange.authority == authority.key() @ ToraError::Unauthorized,
    )]
    pub exchange: Account<'info, Exchange>,
    #[account(mut)]
    pub license: Account<'info, License>,
    /// CHECK: Escrow PDA — verified by seeds
    #[account(
        mut,
        seeds = [b"escrow", license.key().as_ref()],
        bump,
    )]
    pub escrow: SystemAccount<'info>,
    #[account(mut)]
    pub authority: Signer<'info>,
    /// CHECK: Supplier wallet for potential payout
    #[account(mut, constraint = supplier.key() == license.supplier @ ToraError::WrongSupplier)]
    pub supplier: AccountInfo<'info>,
    /// CHECK: Buyer wallet for potential refund
    #[account(mut, constraint = buyer.key() == license.buyer @ ToraError::Unauthorized)]
    pub buyer: AccountInfo<'info>,
    pub system_program: Program<'info, System>,
}

/// SC-03 FIX: Raise dispute — only the buyer can initiate
#[derive(Accounts)]
pub struct RaiseDispute<'info> {
    #[account(
        mut,
        constraint = license.buyer == buyer.key() @ ToraError::Unauthorized,
    )]
    pub license: Account<'info, License>,
    pub buyer: Signer<'info>,
}

#[derive(Accounts)]
pub struct VerifyLicense<'info> {
    #[account(mut)]
    pub license: Account<'info, License>,
}

#[derive(Accounts)]
pub struct ExpireLicense<'info> {
    #[account(mut)]
    pub license: Account<'info, License>,
}

#[derive(Accounts)]
pub struct DeactivateListing<'info> {
    #[account(
        mut,
        constraint = listing.supplier == supplier.key() @ ToraError::Unauthorized,
    )]
    pub listing: Account<'info, Listing>,
    pub supplier: Signer<'info>,
}

/// V-24 FIX: Close instruction for listings — reclaims rent to supplier
#[derive(Accounts)]
pub struct CloseListing<'info> {
    #[account(
        mut,
        close = supplier,  // V-24 FIX: SOL rent returned to supplier on close
        constraint = listing.supplier == supplier.key() @ ToraError::Unauthorized,
        constraint = !listing.is_active @ ToraError::ListingStillActive,
    )]
    pub listing: Account<'info, Listing>,
    #[account(mut)]
    pub supplier: Signer<'info>,
}

/// V-24 FIX: Close instruction for licenses — reclaims rent to buyer
#[derive(Accounts)]
pub struct CloseLicense<'info> {
    #[account(
        mut,
        close = buyer,   // V-24 FIX: SOL rent returned to buyer on close
        constraint = license.buyer == buyer.key() @ ToraError::Unauthorized,
        constraint = !license.is_active @ ToraError::LicenseStillActive,
        constraint = license.is_released || license.supplier_escrowed == 0 @ ToraError::EscrowNotEmpty,
    )]
    pub license: Account<'info, License>,
    #[account(mut)]
    pub buyer: Signer<'info>,
}

#[derive(Accounts)]
pub struct UpdateFees<'info> {
    #[account(
        mut,
        seeds = [b"exchange"],
        bump = exchange.bump,
        constraint = exchange.authority == authority.key() @ ToraError::Unauthorized,
    )]
    pub exchange: Account<'info, Exchange>,
    pub authority: Signer<'info>,
}

// ═══════════════════════════════════════════════════════════════
// ERRORS
// ═══════════════════════════════════════════════════════════════

#[error_code]
pub enum ToraError {
    #[msg("Fee basis points too high (max 5000 = 50%)")]
    FeeTooHigh,
    #[msg("String exceeds maximum length")]
    StringTooLong,
    #[msg("Price must be greater than 0")]
    InvalidPrice,
    #[msg("License duration must be 1-12 months")]
    InvalidDuration,
    #[msg("Listing is not active")]
    ListingInactive,
    #[msg("Arithmetic overflow")]
    Overflow,
    #[msg("Unauthorized")]
    Unauthorized,
    #[msg("Wrong supplier account")]
    WrongSupplier,
    #[msg("Wrong platform treasury account")]
    WrongTreasury,
    // V-11 FIX: Explicit error for wrong partner treasury
    #[msg("Wrong partner treasury — must match exchange.partner_treasury")]
    WrongPartnerTreasury,
    // V-10 FIX: License expiry errors
    #[msg("License has expired")]
    LicenseExpired,
    #[msg("License is not active")]
    LicenseInactive,
    #[msg("License has not yet expired")]
    LicenseNotYetExpired,
    // V-12 FIX: Escrow/payment flow errors
    #[msg("Escrow has already been released")]
    AlreadyReleased,
    #[msg("A dispute is in progress — contact TORA Exchange support")]
    DisputeInProgress,
    #[msg("Nothing to release from escrow")]
    NothingToRelease,
    #[msg("48-hour refund window has expired")]
    RefundWindowExpired,
    // V-24 FIX: Close instruction safety errors
    #[msg("Listing is still active — deactivate before closing")]
    ListingStillActive,
    #[msg("License is still active — expire before closing")]
    LicenseStillActive,
    #[msg("Escrow is not empty — release or refund before closing")]
    EscrowNotEmpty,
    // SC-03 FIX: Dispute initiation errors
    #[msg("License is already disputed")]
    AlreadyDisputed,
    #[msg("Payment has already been released — cannot dispute")]
    PaymentAlreadyReleased,
}
